name: Deploy to Heroku

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      HEROKU_APP_NAME: "your-heroku-app-name"
      HEROKU_API_KEY: "your-heroku-api-key"
      HEROKU_EMAIL: "your-heroku-email"
      HEROKU_TEAM_NAME: "your-heroku-team-name"

    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v4

      - name: Delete unnecessary directories and files
        run: |
          # Directories to delete
          for dir in bot qBittorrent web; do
            if [ -d "./$dir" ]; then
              echo "Deleting directory: $dir"
              rm -rf ./$dir
            else
              echo "Directory not found: $dir"
            fi
          done

          # Delete a2c.conf if it exists
          if [ -f "./a2c.conf" ]; then
            echo "Deleting file: a2c.conf"
            rm -f ./a2c.conf
          else
            echo "File not found: a2c.conf"
          fi

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ env.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{ env.HEROKU_EMAIL }}
          usedocker: true
          appdir: "."
          process_type: web

      - name: Restart Heroku App
        run: |
          heroku restart --app ${{ env.HEROKU_APP_NAME }}
